#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated Nov 7 2022
#################################################################


#################################################################
# Make Pop VCF


#!/bin/bash

#PBS -l walltime=10:00:00,select=1:ncpus=16:mem=50gb
#PBS -N make_pop_vcf_batch
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o make_pop_vcf_batch.out.txt
#PBS -e make_pop_vcf_batch.err.txt

################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate samtools

cd $PBS_O_WORKDIR
for f1 in /scratch/st-angert-1/22_pi_demo_parse/baseline_pop/*csv; 

do
base_vcf=`basename $f1 .csv`

bcftools view -S $f1 -Oz -o /scratch/st-angert-1/22_pi_demo_parse/$base_vcf".vcf.gz" /scratch/st-angert-1/18_beagle/beagle_output.vcf.gz --threads 16
sleep 20

done

conda deactivate

