#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 7  2021
#################################################################


#################################################################
# Base recalibrator 525 NS.1493.004.IDT_i7_127---IDT_i5_127.76 



#!/bin/bash
 
#PBS -l walltime=05:00:00,select=1:ncpus=1:mem=170gb
#PBS -N base_recal_525
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o base_recal_525.output.txt
#PBS -e base_recal_525.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk BaseRecalibrator -I /scratch/st-angert-1/apply_bqsr/NS.1493.004.IDT_i7_127---IDT_i5_127.76_recal_marked_rg.sort.bam -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa --known-sites /scratch/st-angert-1/gold_set/filtered_snp/gold_filtered_snps_passed.vcf.gz --known-sites /scratch/st-angert-1/gold_set/filtered_indel/gold_filtered_indels_passed.vcf.gz -O /scratch/st-angert-1/base_recal_2/base_recal_NS.1493.004.IDT_i7_127---IDT_i5_127.76.table

conda deactivate


