#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 6  2021
#################################################################


#################################################################
# Select snp variants chr2 



#!/bin/bash
 
#PBS -l walltime=00:20:00,select=1:ncpus=1:mem=32gb
#PBS -N select_snp_chr2
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o select_snp_chr2.output.txt
#PBS -e select_snp_chr2.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk SelectVariants -V /scratch/st-angert-1/genotypeGVCF/gold/gold_chr2.vcf.gz -select-type SNP -O /scratch/st-angert-1/gold_set/snp/gold_chr2_snps.vcf.gz

conda deactivate


