#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 6  2021
#################################################################


#################################################################
# Select indel variants chrXX 



#!/bin/bash
 
#PBS -l walltime=00:20:00,select=1:ncpus=1:mem=32gb
#PBS -N select_indel_chrXX
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o select_indel_chrXX.output.txt
#PBS -e select_indel_chrXX.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk SelectVariants -V /scratch/st-angert-1/genotypeGVCF/gold/gold_chrXX.vcf.gz -select-type INDEL  -O /scratch/st-angert-1/gold_set/indel/gold_chrXX_indels.vcf.gz

conda deactivate


