#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 7  2021
#################################################################


#################################################################
# ApplyBSQR Test 


#!/bin/bash
 
#PBS -l walltime=24:00:00,select=1:ncpus=1:mem=170gb
#PBS -N apply_bqsr_test
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o apply_bqsr_test.output.txt
#PBS -e apply_bqsr_test.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk ApplyBQSR -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa -I /scratch/st-angert-1/RG_Bam/NS.1480.001.IDT_i7_100---IDT_i5_100.83_marked_rg.sorted.bam --bqsr-recal-file /scratch/st-angert-1/base_recal/test_base_recal.table -O /scratch/st-angert-1/apply_bqsr/apply_bqsr_test_marked_rg.sort.bam
 
conda deactivate


