#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 7 2021
#################################################################


#################################################################
# Apply_bqsr  264 NS.1481.002.IDT_i7_189---IDT_i5_189.579 



#!/bin/bash
 
#PBS -l walltime=03:00:00,select=1:ncpus=1:mem=170gb
#PBS -N apply_bqsr_264
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o apply_bqsr_264.output.txt
#PBS -e apply_bqsr_264.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk ApplyBQSR -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa -I /project/st-angert-1/RG_Bam_2/NS.1481.002.IDT_i7_189---IDT_i5_189.579_marked_rg.sorted.bam --bqsr-recal-file /scratch/st-angert-1/base_recal/base_recal_NS.1481.002.IDT_i7_189---IDT_i5_189.579.table -O /scratch/st-angert-1/apply_bqsr/NS.1481.002.IDT_i7_189---IDT_i5_189.579_recal_marked_rg.sort.bam

conda deactivate


