#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 7 2021
#################################################################


#################################################################
# Apply_bqsr  248 NS.1481.002.IDT_i7_174---IDT_i5_174.941 



#!/bin/bash
 
#PBS -l walltime=03:00:00,select=1:ncpus=1:mem=170gb
#PBS -N apply_bqsr_248
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o apply_bqsr_248.output.txt
#PBS -e apply_bqsr_248.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk ApplyBQSR -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa -I /project/st-angert-1/RG_Bam_2/NS.1481.002.IDT_i7_174---IDT_i5_174.941_marked_rg.sorted.bam --bqsr-recal-file /scratch/st-angert-1/base_recal/base_recal_NS.1481.002.IDT_i7_174---IDT_i5_174.941.table -O /scratch/st-angert-1/apply_bqsr/NS.1481.002.IDT_i7_174---IDT_i5_174.941_recal_marked_rg.sort.bam

conda deactivate


