#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated Feb 18 2021
#################################################################


#################################################################
#Index M. cardinalis genome



#!/bin/bash
 
#PBS -l walltime=00:10:00,select=1:ncpus=18:mem=4gb
#PBS -N trimtest
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o /scratch/st-angert-1/reports/index.output.txt
#PBS -e /scratch/st-angert-1/reports/index.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate bwa


cd $PBS_O_WORKDIR


/usr/bin/time --verbose bwa index /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa  


conda deactivate 


