#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 13  2021
#################################################################


#################################################################
# Dropping genotype information for  snps chrXX 



#!/bin/bash
 
#PBS -l walltime=00:20:00,select=1:ncpus=1:mem=32gb
#PBS -N sites_snp_chrXX
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o make_sites_snp_chrXX.output.txt
#PBS -e make_sites_snp_chrXX.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk MakeSitesOnlyVcf -I /scratch/st-angert-1/gold_set2/7a_select_variants/snp/gold_chrXX_snps_filtered_pass.vcf.gz -O /scratch/st-angert-1/gold_set2/7b_make_sites/snp/gold_chrXX_snps_filtered_pass_sites.vcf.gz

conda deactivate


