#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 11  2021
#################################################################


#################################################################
# Genomics DBImport per chromsome, per 5M bp 



#!/bin/bash
 
#PBS -l walltime=20:00:00,select=1:ncpus=1:mem=170gb
#PBS -N gGVCF_all_chr5_25000001_30000000
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o gGVCF_all_chr5_25000001_30000000.output.txt
#PBS -e gGVCF_all_chr5_25000001_30000000.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk GenotypeGVCFs -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa -V gendb://"/scratch/st-angert-1/2_db_import/chr5_25000001_30000000" -O /scratch/st-angert-1/3_genotypeGVCF/gvcf_all_chr5_25000001_30000000.vcf.gz


conda deactivate


