#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated March 23 2021
#################################################################


#################################################################
# Marked Duplicates for individual sample



#!/bin/bash
 
#PBS -l walltime=01:00:00,select=1:ncpus=1:mem=32gb
#PBS -N mark_i
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o mark_i.output.txt
#PBS -e mark_i.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4


cd $PBS_O_WORKDIR

picard MarkDuplicates I=/scratch/st-angert-1/missing/NS.1489.004.IDT_i7_184---IDT_i5_184.93.sorted.bam O=/scratch/st-angert-1/mark/NS.1489.004.IDT_i7_184---IDT_i5_184.93_marked.sorted.bam M=/scratch/st-angert-1/mark/NS.1489.004.IDT_i7_184---IDT_i5_184.93_marked_dup_metrics.txt


conda deactivate


