#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated April 30  2021
#################################################################


#################################################################
# Genomics DBImport per chromsome, per 5M bp 



#!/bin/bash
 
#PBS -l walltime=02:00:00,select=1:ncpus=30:mem=170gb
#PBS -N gGVCF_gold_chrXX_YY_ZZ
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o gGVCF_gold_chrXX_YY_ZZ.output.txt
#PBS -e gGVCF_gold_chrXX_YY_ZZ.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk GenotypeGVCFs -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa -V gendb://"/scratch/st-angert-1/db_import/db_import_gold/gold_chrXX_YY_ZZ" -O /scratch/st-angert-1/genotypeGVCF/gvcf_gold_chrXX_YY_ZZ.vcf.gz


conda deactivate


