#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 20  2021
#################################################################


#################################################################
# Extract snp coverage chr5 



#!/bin/bash
 
#PBS -l walltime=01:20:00,select=1:ncpus=1:mem=100gb
#PBS -N hard_filter_snp_chr5
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o hard_filter_snp_chr5.output.txt
#PBS -e hard_filter_snp_chr5.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk VariantFiltration -V /scratch/st-angert-1/gold_set/snp/gold_chr5_snps.vcf.gz --filter-expression "MQ < 50.0 || AN < 21.6 || SOR < -1.0 || SOR > 1.0 || AF < 0.25 || AF > 0.75 || ExcessHet > 10.0 || BaseQRankSum < -1.0 || BaseQRankSum > 1.0 || DP < 6.137418 || DP > 236.1686" --filter-name "My_Filters" --missing-values-evaluate-as-failing true -O /scratch/st-angert-1/gold_set/filtered_snp/gold_chr5_snps_filtered.vcf.gz


conda deactivate


