#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated April 27  2021
#################################################################


#################################################################
# Genomics DBImport per chromsome, per 5M bp 



#!/bin/bash
 
#PBS -l walltime=06:00:00,select=1:ncpus=30:mem=170gb
#PBS -N db_chr2_50000001_53456921
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o db_chr2_50000001_53456921.output.txt
#PBS -e db_chr2_50000001_53456921.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk GenomicsDBImport --genomicsdb-workspace-path /scratch/st-angert-1/2_db_import/chr2_50000001_53456921 --batch-size 665 -L CE10_chr2:50000001-53456921 --sample-name-map /project/st-angert-1/list/Genomics_Import_All.sample_map --reader-threads 30

conda deactivate


