#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 11 2021
#################################################################


#################################################################
# Select snp variants chr4 



#!/bin/bash
 
#PBS -l walltime=24:00:00,select=1:ncpus=1:mem=170gb
#PBS -N select_snp_chr4
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o select_snp_chr4.output.txt
#PBS -e select_snp_chr4.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk SelectVariants -V /scratch/st-angert-1/4_gather_VCF/chr4_raw_var.vcf.gz -select-type SNP -O /scratch/st-angert-1/5_select_var/snp/chr4_snp_raw_var.vcf.gz

conda deactivate


