#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 11 2021
#################################################################


#################################################################
# Gather VCF chromosome 4  



#!/bin/bash
 
#PBS -l walltime=02:00:00,select=1:ncpus=1:mem=64gb
#PBS -N gather_VCF_chr4
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o gather_VCF_chr4.output.txt
#PBS -e gather_VCF_chr4.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk GatherVcfs --arguments_file /scratch/st-angert-1/scripts/4_gather_VCF/gather_VCF_In_chr4.csv -O /scratch/st-angert-1/4_gather_VCF/chr4_raw_var.vcf.gz  

gatk IndexFeatureFile -I /scratch/st-angert-1/4_gather_VCF/chr4_raw_var.vcf.gz

conda deactivate


