#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated April 30  2021
#################################################################


#################################################################
# Genomics DBImport per chromsome, per 5M bp 



#!/bin/bash
 
#PBS -l walltime=24:00:00,select=1:ncpus=1:mem=64gb
#PBS -N gather_VCF_chr7
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o gather_VCF_chr7.output.txt
#PBS -e gather_VCF_chr7.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk GatherVcfs --arguments_file /scratch/st-angert-1/scripts/gather_VCF/gather_VCF_In_chr7.csv -O /scratch/st-angert-1/genotypeGVCF/gold 

conda deactivate


