#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated June 01  2021
#################################################################


#################################################################
# Apply VQSR for SNPs 



#!/bin/bash
 
#PBS -l walltime=10:00:00,select=1:ncpus=1:mem=170gb
#PBS -N snp_ApplyVQSR_chr1
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o ApplyVQSR_snp_chr1.output.txt
#PBS -e ApplyVQSR_snp_chr1.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk ApplyVQSR --mode SNP -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa -V /scratch/st-angert-1/5_select_var/snp/chr1_snp_raw_var.vcf.gz  --recal-file /scratch/st-angert-1/8_var_recal/snp/snp.recal.vcf.gz --truth-sensitivity-filter-level 50.0 --tranches-file /scratch/st-angert-1/8_var_recal/snp/snp_output.tranches --create-output-variant-index true --output /scratch/st-angert-1/9_applyVQSR/all_var_vqsr_snp_chr1.vcf

conda deactivate


