#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated Nov 7 2022
#################################################################


#################################################################
# Make Pop VCF


#!/bin/bash

#PBS -l walltime=03:30:00,select=1:ncpus=1:mem=100gb
#PBS -N pi_pop_vcf_batch
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o pi_pop_vcf_batch.out.txt
#PBS -e pi_pop_vcf_batch.err.txt

################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

for f1 in /scratch/st-angert-1/22_pi_demo_parse/baseline_pop/*csv; 

do
base_vcf=`basename $f1 .csv`


vcftools --gzvcf /scratch/st-angert-1/22_pi_demo_parse/$base_vcf".vcf.gz" --site-pi --out /scratch/st-angert-1/23_pi_demo/$base_vcf

sleep 10


done

conda deactivate

