#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated June 01  2021
#################################################################


#################################################################
# Apply VQSR for SNPs 



#!/bin/bash
 
#PBS -l walltime=10:00:00,select=1:ncpus=1:mem=170gb
#PBS -N indel_ApplyVQSR
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o ApplyVQSR_indel.output.txt
#PBS -e ApplyVQSR_indel.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk ApplyVQSR --mode SNP -R /scratch/st-angert-1/mc_ref/CE10g_v2.0.fa --arguments_file /scratch/st-angert-1/5_select_var/indel/all_indel_raw_chr_list.csv  --recal-file /scratch/st-angert-1/8_var_recal/indel/indel.recal.vcf.gz --truth-sensitivity-filter-level 50.0 --tranches-file /scratch/st-angert-1/8_var_recal/indel/indel_output.tranches --create-output-variant-index true --output /scratch/st-angert-1/9_applyVQSR/all_var_vqsr_indel.vcf.gz

conda deactivate


