#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 6  2021
#################################################################


#################################################################
# Extract snp coverage chrXX 



#!/bin/bash
 
#PBS -l walltime=01:20:00,select=1:ncpus=1:mem=100gb
#PBS -N hard_filter_snp_chrXX
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o hard_filter_snp_chrXX.output.txt
#PBS -e hard_filter_snp_chrXX.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk VariantFiltration -V /scratch/st-angert-1/gold_set/snp/gold_chrXX_snps.vcf.gz --filter-expression "MQ > 50.0" --filter-name "mapping_quality" --filter-expression "AN > 24*0.9" --filter-name "cov_chr" --filter-expression "SOR > -1.0" --filter-name "strand_odds_ratio_-1" --filter-expression "SOR < 1.0" --filter-name "strand_odds_ratio_1" --filter-expression "AF > 0.25" --filter-name "minor_allele_freq" --filter-expression "ExcessHet < 10" --filter-name "Excess_H" --filter-expression "BaseQRankSum > -1.0" --filter-name "BaseQRankSum_-1" --filter-expression "BaseQRankSum < 1.0" --filter-name "BaseQRankSum_1" --filter-expression "DP > YY" --filter-name "Upper_DP" --filter-expression "DP > ZZ" --filter-name "Lower_DP" -O /scratch/st-angert-1/gold_set/filtered_snp/gold_chrXX_snps_filtered.vcf.gz

conda deactivate


