#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated March 23 2021
#################################################################


#################################################################
#Remove Marked Duplicates for 12 test samples



#!/bin/bash
 
#PBS -l walltime=40:00:00,select=1:ncpus=1:mem=16gb
#PBS -N mark_0
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o mark_0.output.txt
#PBS -e mark_0.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4


cd $PBS_O_WORKDIR

FILE=/project/st-angert-1/raw_data/all_raw/all_raw_0.csv

while IFS=, read -r f1;
do

picard MarkDuplicates I=/project/st-angert-1/raw_bam/$f1".sorted.bam" O=/scratch/st-angert-1/mark/$f1"_marked.sorted.bam" M=/scratch/st-angert-1/mark/$f1"marked_dup_metrics.txt"

done < $FILE

conda deactivate


