#################################################################
#Population Genomic Analysis pipeline for Mimulus cardinalis

#Author: Daniel Anstett
#Last updated May 12  2021
#################################################################


#################################################################
# Select snp variants chr7 



#!/bin/bash
 
#PBS -l walltime=00:20:00,select=1:ncpus=1:mem=32gb
#PBS -N select_snp_chr7
#PBS -A st-angert-1
#PBS -m abe
#PBS -M daniel.anstett@botany.ubc.ca
#PBS -o select_snp_chr7.output.txt
#PBS -e select_snp_chr7.error.txt
 
################################################################################

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gatk4

cd $PBS_O_WORKDIR

gatk SelectVariants -V /scratch/st-angert-1/gold_set2/genotypeGVCF/gold_chr7.vcf.gz -select-type SNP  -O /scratch/st-angert-1/gold_set2/gold_snp/gold_chr7_snp.vcf.gz

gatk IndexFeatureFile -I /scratch/st-angert-1/gold_set2/gold_snp/gold_chr7_snp.vcf.gz

gatk VariantsToTable -V /scratch/st-angert-1/gold_set2/gold_snp/gold_chr7_snp.vcf.gz -O /scratch/st-angert-1/gold_set2/gold_snp/cov_snp2_chr7.tsv -F CHROM -F POS -F TYPE -F DP 

conda deactivate


